version: '3.7'

services:
  breath-server:
    image: breath-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/breath-server/src
      - ./data:/home/breath-server/data
    container_name: breath-server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start