CREATE TABLE IF NOT EXISTS air_quality_log (
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id TEXT NOT NULL,
  rco2 INT,
  pm02 INT,
  tvoc INT,
  nox INT,
  atmp REAL,
  rhum REAL
);

CREATE TABLE IF NOT EXISTS sensors (
  id TEXT NOT NULL UNIQUE,
  name TEXT,
  has_rco2 BOOLEAN NOT NULL DEFAULT 0,
  has_pm02 BOOLEAN NOT NULL DEFAULT 0,
  has_tvoc BOOLEAN NOT NULL DEFAULT 0,
  has_nox BOOLEAN NOT NULL DEFAULT 0,
  has_atmp BOOLEAN NOT NULL DEFAULT 0,
  has_rhum BOOLEAN NOT NULL DEFAULT 0
)